"""empty message

Revision ID: 3178c237522d
Revises: e32a83a09ba0
Create Date: 2025-05-05 17:11:09.375732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3178c237522d'
down_revision = 'e32a83a09ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_category_name_uc', ['name', 'user_id'])

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('_user_category_name_uc', type_='unique')

    # ### end Alembic commands ###
