"""empty message

Revision ID: e32a83a09ba0
Revises: 9d0d558a6888
Create Date: 2025-05-05 16:54:45.679905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32a83a09ba0'
down_revision = '9d0d558a6888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_format')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('date_format')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_format', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_format', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
